$.ABI = function() {};
$.ABI.prototype = (function() {
    var setting = {};
    return {
        init: function(options) {
            if (typeof options === "undefined" || options.length < 1) {
                return false;
            }
            setting = $.extend({}, setting, options);
        },
        getBreezySwapV1ABI() {
            return [
                {
                   "inputs":[
                      {
                         "internalType":"contract IERC20",
                         "name":"_base",
                         "type":"address"
                      },
                      {
                         "internalType":"contract IERC20",
                         "name":"_token",
                         "type":"address"
                      },
                      {
                         "internalType":"address",
                         "name":"_feeMachineContract",
                         "type":"address"
                      },
                      {
                         "internalType":"contract IBreezyWhitelist",
                         "name":"_whitelistContract",
                         "type":"address"
                      },
                      {
                         "internalType":"string",
                         "name":"name",
                         "type":"string"
                      },
                      {
                         "internalType":"string",
                         "name":"symbol",
                         "type":"string"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"constructor"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"owner",
                         "type":"address"
                      },
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"spender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"value",
                         "type":"uint256"
                      }
                   ],
                   "name":"Approval",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"previousOwner",
                         "type":"address"
                      },
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"newOwner",
                         "type":"address"
                      }
                   ],
                   "name":"OwnershipTransferred",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"account",
                         "type":"address"
                      }
                   ],
                   "name":"Paused",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"from",
                         "type":"address"
                      },
                      {
                         "indexed":true,
                         "internalType":"address",
                         "name":"to",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"value",
                         "type":"uint256"
                      }
                   ],
                   "name":"Transfer",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"account",
                         "type":"address"
                      }
                   ],
                   "name":"Unpaused",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"mintLP",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onAddLP",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"amountLP",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseOutputAmout",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onRemoveLP",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"minTokenOutput",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onSwapBaseToTokenWithBaseInput",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"maxBaseInput",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onSwapBaseToTokenWithTokenOutput",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"maxTokenInput",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onSwapTokenToBaseWithBaseOutput",
                   "type":"event"
                },
                {
                   "anonymous":false,
                   "inputs":[
                      {
                         "indexed":false,
                         "internalType":"address",
                         "name":"sender",
                         "type":"address"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"minBaseOutput",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"baseOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolBaseBalance",
                         "type":"uint256"
                      },
                      {
                         "indexed":false,
                         "internalType":"uint256",
                         "name":"poolTokenBalance",
                         "type":"uint256"
                      }
                   ],
                   "name":"onSwapTokenToBaseWithTokenInput",
                   "type":"event"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"PLATFORM_FEE",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"TRADE_FEE",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"minLP",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"maxTokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"addLP",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"owner",
                         "type":"address"
                      },
                      {
                         "internalType":"address",
                         "name":"spender",
                         "type":"address"
                      }
                   ],
                   "name":"allowance",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"spender",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"amount",
                         "type":"uint256"
                      }
                   ],
                   "name":"approve",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"account",
                         "type":"address"
                      }
                   ],
                   "name":"balanceOf",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"base",
                   "outputs":[
                      {
                         "internalType":"contract IERC20",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"amount",
                         "type":"uint256"
                      }
                   ],
                   "name":"burn",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"account",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"amount",
                         "type":"uint256"
                      }
                   ],
                   "name":"burnFrom",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"decimals",
                   "outputs":[
                      {
                         "internalType":"uint8",
                         "name":"",
                         "type":"uint8"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"spender",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"subtractedValue",
                         "type":"uint256"
                      }
                   ],
                   "name":"decreaseAllowance",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"feeMachineContract",
                   "outputs":[
                      {
                         "internalType":"address",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"tokenOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseReserve",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"tokenReserve",
                         "type":"uint256"
                      }
                   ],
                   "name":"getBaseInputAmountFromTokenOutput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"pure",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      }
                   ],
                   "name":"getBaseOutput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseReserve",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"tokenReserve",
                         "type":"uint256"
                      }
                   ],
                   "name":"getBaseOutputAmountFromTokenInput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"pure",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      }
                   ],
                   "name":"getDataFromBaseInputToAddLp",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      }
                   ],
                   "name":"getDataFromTokenInputToAddLp",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"amountLP",
                         "type":"uint256"
                      }
                   ],
                   "name":"getDataToRemoveLP",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"getK",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"baseOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseReserve",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"tokenReserve",
                         "type":"uint256"
                      }
                   ],
                   "name":"getTokenInputAmountFromBaseOutput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"pure",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      }
                   ],
                   "name":"getTokenOutput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseReserve",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"tokenReserve",
                         "type":"uint256"
                      }
                   ],
                   "name":"getTokenOutputAmountFromBaseInput",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"pure",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"getTotalReserve",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"spender",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"addedValue",
                         "type":"uint256"
                      }
                   ],
                   "name":"increaseAllowance",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"name",
                   "outputs":[
                      {
                         "internalType":"string",
                         "name":"",
                         "type":"string"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"owner",
                   "outputs":[
                      {
                         "internalType":"address",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"pause",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"paused",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"platformFundAddress",
                   "outputs":[
                      {
                         "internalType":"address",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"amountLP",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"minBaseOutput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"minTokenOutput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"removeLP",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"renounceOwnership",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"_feeMachineContract",
                         "type":"address"
                      }
                   ],
                   "name":"setFeeMachineContract",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"_platformFee",
                         "type":"uint256"
                      }
                   ],
                   "name":"setPlatformFee",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"newAddress",
                         "type":"address"
                      }
                   ],
                   "name":"setPlatformFundAdress",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"_tradeFee",
                         "type":"uint256"
                      }
                   ],
                   "name":"setTradeFee",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"_whitelistContract",
                         "type":"address"
                      }
                   ],
                   "name":"setWhitelistContract",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"baseInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"minTokenOutput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"swapBaseToTokenWithBaseInput",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"maxBaseInput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"tokenOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"swapBaseToTokenWithTokenOutput",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"maxTokenInput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"baseOutputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"swapTokenToBaseWithBaseOutput",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"uint256",
                         "name":"tokenInputAmount",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"minBaseOutput",
                         "type":"uint256"
                      },
                      {
                         "internalType":"uint256",
                         "name":"deadline",
                         "type":"uint256"
                      }
                   ],
                   "name":"swapTokenToBaseWithTokenInput",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"symbol",
                   "outputs":[
                      {
                         "internalType":"string",
                         "name":"",
                         "type":"string"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"token",
                   "outputs":[
                      {
                         "internalType":"contract IERC20",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"totalSupply",
                   "outputs":[
                      {
                         "internalType":"uint256",
                         "name":"",
                         "type":"uint256"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"to",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"amount",
                         "type":"uint256"
                      }
                   ],
                   "name":"transfer",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"from",
                         "type":"address"
                      },
                      {
                         "internalType":"address",
                         "name":"to",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"amount",
                         "type":"uint256"
                      }
                   ],
                   "name":"transferFrom",
                   "outputs":[
                      {
                         "internalType":"bool",
                         "name":"",
                         "type":"bool"
                      }
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      {
                         "internalType":"address",
                         "name":"newOwner",
                         "type":"address"
                      }
                   ],
                   "name":"transferOwnership",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"unpause",
                   "outputs":[
                      
                   ],
                   "stateMutability":"nonpayable",
                   "type":"function"
                },
                {
                   "inputs":[
                      
                   ],
                   "name":"whitelistContract",
                   "outputs":[
                      {
                         "internalType":"contract IBreezyWhitelist",
                         "name":"",
                         "type":"address"
                      }
                   ],
                   "stateMutability":"view",
                   "type":"function"
                }
             ];
        },
        getBreezySwapperABI() {
            return [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[{"internalType":"contract IERC20","name":"token","type":"address"},{"internalType":"contract IBreezySwapV1BREWETH","name":"pair","type":"address"}],"name":"approveWithPair","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"token1InputAmount","type":"uint256"},{"internalType":"contract IBreezySwapV1BREWETH","name":"token1Pair","type":"address"},{"internalType":"contract IBreezySwapV1BREWETH","name":"token2Pair","type":"address"}],"name":"getTokenOutput","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"token1InputAmount","type":"uint256"},{"internalType":"uint256","name":"minToken2Output","type":"uint256"},{"internalType":"address","name":"token1PairAddress","type":"address"},{"internalType":"address","name":"token2PairAddress","type":"address"},{"internalType":"uint256","name":"deadline","type":"uint256"}],"name":"swapTokenToTokenWithTokenInput","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}];
        },
        getERC20TokenABI() {
            return [{"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"symbol","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType":"address","name":"spender","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"inputs":[{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"spender","type":"address"}],"name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mint","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
        },
    };
}(jQuery));